server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://employee-mysql:3306/user_service_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

keycloak:
  server-url: http://keycloak:8080
  realm: employee-platform
  client-id: user-service
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG