server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db
    username: root
    password: Kalyan@18

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

jwt:
  secret: 3mQvYg2GmP0dQmV6QmV0dGVyVGhhbkEgWW91VHViZVNlY3JldEtleUZvckRlbW8xMjM0NTY3ODkw
  expiration: 86400000
